### ISSUE TITLE
Error running in Keras and TensorFlow with CORAL

### ISSUE THREAD

**Issue by ukamath** [wzell/mann#4]
Hello

After I modified mann_sentiment_analysis.py file for having the right version of Keras Visualization, the first neural network model ran but the CORAL failed with the exception below. Has anyone seen this? What is the fix? Thanks a lot for this nice package!!

Keras version - 2.1.5
TensorFlow version - 1.6.0

Exception

2018-09-03 18:35:33.550985: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
NN: 0.562929061785
Traceback (most recent call last):
  File "sentiment_analysis.py", line 162, in <module>
    nn_coral.fit(x_s_tr, y_s_tr, x_t_tr, verbose=0, init_weights='nn')
  File "/Users/udaykamath/mann/models/mann_sentiment_analysis.py", line 108, in fit
    self.create()
  File "/Users/udaykamath/mann/models/mann_sentiment_analysis.py", line 72, in create
    encoded_s = encoding(input_s)
  File "/Users/udaykamath/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 661, in __call__
    regularization_losses = [self.activity_regularizer(x) for x in _to_list(output)]
  File "/Users/udaykamath/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 661, in <listcomp>
    regularization_losses = [self.activity_regularizer(x) for x in _to_list(output)]
  File "/Users/udaykamath/mann/models/correlation_alignment.py", line 55, in __call__
    raise Exception('Need to call `set_layer` on '
Exception: Need to call `set_layer` on ActivityRegularizer instance before calling the instance.

**Comment by ukamath** [comment]
I could get it working by changing the code in mann_sentiment_analysis.py

 # layers
        if self.activity_regularizer:
            encoding = Dense(self.n_hiddens,
                             activation='sigmoid',
                             name='encoded'
                             )
            self.activity_regularizer.set_layer(encoding)
            
        else:
            encoding = Dense(self.n_hiddens,
                             activation='sigmoid',
                             name='encoded')
        prediction = Dense(2,
                           activation='softmax',
                           name='pred')
        # encoding
        encoded_s = encoding(input_s)
        encoded_t = encoding(input_t)
        # prediction
        pred_s = prediction(encoded_s)
        pred_t = prediction(encoded_t)
        # model definition
        self.nn = Model(input=[input_s,input_t],
                        output=[pred_s,pred_t])
        if self.activity_regularizer:
            self.nn.get_layer('encoded').activity_regularizer=self.activity_regularizer

**Comment by wzell** [comment]
Thank you for the solution!
