### ISSUE TITLE
Need to call `set_layer` on ActivityRegularizer instance before calling the instance

### ISSUE THREAD

**Issue by younglululu** [wzell/mann#5]
When I tried to run 'mann_sentiment_analysis.py', I encountered the following error:

Traceback (most recent call last):
  File "sentiment_analysis.py", line 162, in <module>
    nn_coral.fit(x_s_tr, y_s_tr, x_t_tr, verbose=0, init_weights='nn')
  File "/home/yanglu/Downloads/mann-master/models/mann_sentiment_analysis.py", line 108, in fit
    self.create()
  File "/home/yanglu/Downloads/mann-master/models/mann_sentiment_analysis.py", line 72, in create
    encoded_s = encoding(input_s)
  File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 645, in __call__
  File "/home/yanglu/Downloads/mann-master/models/correlation_alignment.py", line 55, in __call__
    raise Exception('Need to call `set_layer` on '
Exception: Need to call `set_layer` on ActivityRegularizer instance before calling the instance.

It seems that the set_layer function hasn't been called by the Regularizer. My keras version if 2.1.2, I am wondering how could I fix this? Thanks!

**Comment by wzell** [comment]
Hallo younglululu,

Nice to see your interest in our project!

The code is for Keras 1.1.0. Please try this version or see artificial_example.py how to port the approach to newer versions!

**Comment by wzell** [comment]
I close this issue as it seems to be a version problem.
